name: Update MovieBoxPro Metadata

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # This prevents using the default GITHUB_TOKEN for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python update_movieboxpro.py

      - name: Commit changes if updated
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Set your Git config with your username
          git config --global user.email "Fjam1571@users.noreply.github.com"
          git config --global user.name "Fjam1571"
          # Update the remote URL to use your PAT instead of the default token
          git remote set-url origin https://Fjam1571:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          if [ -n "$(git status --porcelain Sources/MovieBoxPro.json)" ]; then
            git add Sources/MovieBoxPro.json
            git commit -m "Update MovieBoxPro metadata $(date -u)"
            git push
          else
            echo "No changes detected."
          fi
